language: node_js
deploy:
  provider: npm
  email: npm@smart-coordination.com
  api_key:
    secure: aEsD354SFg+VsL4DpZ3SxBN5xoHtxFoYt6CA9a+k06AsKZlkPeG6Ga7WeqALyzFG0BFLQMnEuOB4oJv+IRX+gzNqi0vt9PwWt8Rgg0uWxff7Wl3WcZBGsM1Bd/b/HL5qAekMXUdou/GTCnhO33cwVRM67uk5T2Hc6rUXOAfLuOkJmsM0dZiOapjlvFjl6U5AIJ9YZKdwOEVTEwsgd4Y+8EdrB2ZMuE3gDlArVMJSWuiW5M1ARXZE2D5LcpAeC1cAvCn+z9tP4ilIa84Ers+ieZKs1aWR1/0GDjB51iznM8aUdmD5MgV4YzUo1uNVqLBJtcS696eiRdtk5UFRDYhELmoTD4t8/DgEGNNy6mVIlosUyN0+TrbJjUaFYkvoEhGzuZFxgRTCbZLd2BUSet4lpnPORd22LDXKv1w5CSy9y7vW7uzBaU4Uj5egPmgmOTu+n5U79unqQXStqsIbeaPqSBEtBpZVlXqzHP9ddo5iSnFw5eIeV/vwuMpjl0Fyp4mXZr7+u3L5VtM04kvto2o8kt+8YGLOlvytE5P0qB/m4/2He22u+xYLIub8b84huaCfpftiw6MFGvpqfs4R7GVWZi3nC3HDSkMEjETAa33XPrIhsc8YwhSIxwI2NO+RVW1PgjzBGsWSBGfMBdW9xVLY680YeylrJ2biNoo2lbEahpM=
  on:
    branch: master
    tags: true
    repo: pushrocks/gulp-addtemplate
