language: node_js
before_install:
- nvm install stable
- node -v
- npm -v
- npm install -g gulp
- npm install gulp
- npm install gulp-typescript
deploy:
  provider: npm
  email: npm@smart-coordination.com
  api_key:
    secure: ojDtOFhgxSt8KyxdTQb8Y/088yWOYvLmL86H9GqijRvVAsaAYTn2kV0f3QKqJT5QlO3NAyZ/p9HcV6XfGxDTxprwdmaf9AVLW8oNV7u/CaUt0Qq8RD0slqwV7edQhDMykkB9rCOYk58FjaoqG5GsbjTNR6lGgt+2re3tIihDL+zh0AdWVXul6/GcWVCIHzIh18/To0/Ds9hqTKrts3/Q6rZXhK0gtY110LTEskEXAOOY98ScfuxQOE1SdWs/c3x1rXYMacWgAwKyBIOPRFAVl46u6VW4pO/FyQHn6QLkPQN8g55W6+jx6Mwi5HbdzbhVIFPcZUjtfUgLYN8MPw4ADTFHyghhnRGjFslKd7maqXOKm1ZAgw1Oyq3lV2dO8dHCtNcZ7y2GEPeJV++uvF1RpxAuRMs/qS+M8X7aaSHGby7tEIwaEyf2ZexHdbj8vYtSK9IGabieaRP7IJY4jNYq+IviVY74jR0jeiynIiXtLd6h3xTbwi4N1prJ8XTJCb4kcMzsjrVWQzs+EE9P6qIwYa2JqlbMIEQdv4gbEbDx6YM0A0rw9CROhc2GYdaCsqAjNZ9XhTlatSZP7vvk1sp6S+D5nBzCDr8HrzuBVjOlNy4+zWQHqGY5Qmuk+VJID/JGhT8MMbFhxgEXhcJKp5gG6iQWuoWP/oBKQvq4PfMU0dk=
  on:
    tags: true
    repo: pushrocks/gulp-addtemplate
notifications:
  slack:
    secure: ldY1Q8VF0blrohUNlVEnRkkUSVhRGZPNPufJei2C2DxilV+F9cV4lRmUaPegeBlQHE6ArrC5JC9tEULepyiUecCVVzZtqxEoJAhFZUBjC79W4AlmWpiA077bjfpjHuoke0jW0xvWiZ5cdBuBB3wxLujyOc0sl8hIzSTmy5pCqTSaxTnl95Aazp4vGc0gz6P6KmvTMxJmtUWYjV1pdX3hVF3ed5krx6F9PG7Cuq9TlJKYjxqRkXM3avIVdSrzHD5cKSWu52PSCXcK3Cy5Lyxon1uKzKuBsHFBu/H6GgFjdDDKmHZaPZ5HerQCwoPirgUshYTUI9Z6rg9esQyELb+xCMLSK54qwGbCSEreqvf0AYrjKwXgWGuhnadclqX/k7H5R+EPXtZItjrQR4gjpKm7lt/nK1aEaaHhlD0sT+g6TKTcLQtsZ71ZgSYzmj2oe+rbYqULJM4IrQm1sm7P+e+xGqR0cjdY0TfmgwuzyxfQdzZGq67tFuM9U8+q0yofx1Kh9TtO6m2fCAiQGNXVrz6Cb2I1kFmVU5NLlA1ykwXrtJDEX1xOYBuDMyj1Cesz71NMQDFuFGhc0fpS//xDQQ/10xNC5mFa3KTLfm3JVb2hJ3TOmgOg5mWMeUuYWbQBMh3cM58BrB/NYrTXRCnXzZNj/6Z9Yx23znxJakAnKn+Qr/Y=
